name: Nuget Develop Prerelease

on:
  push:
    branches:
      - develop

jobs:
  pushprerelease:
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
    steps:
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYYMMDDHHmmss
      - uses: actions/checkout@master
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - uses: olegtarasov/get-tag@v2.1
        id: tagTimeslice
        with:
          tagRegex: "(?<package>.*)-(?<version>.*)"
      - name: Build/Check for compile errors (dotnet build)
        run: dotnet pack -p:PackageVersion=${{ steps.tagTimeslice.outputs.tag }}
      - name: Run Unit Tests (dotnet test)
        run: dotnet test --configuration Release
      - name: Create Package (dotnet pack)
        run: dotnet pack --configuration Release -p:PackageVersion=${{ steps.tagTimeslice.outputs.tag }}
      - name: Setup Nuget.exe
        uses: warrenbuckley/Setup-Nuget@v1
      - name: Nuget push
        run: |
          nuget setApiKey ${{ secrets.TIMESLICE_NUGET_ORG_PUSH_TOKEN }}
          nuget push .\**\**\bin\Release\*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate -NoSymbols
