name: ReSharper

on:
  pull_request: {}

jobs:
  resharper:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: resharper
        working-directory: ./TimeSliceNet
        uses: glassechidna/resharper-action@master
        with:
          solution: TimeSliceNet.sln
