name: Unittests and Coverage

on: [push, pull_request]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup .NET Core
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: 5.0.100
      - name: Run Tests
        working-directory: ./TimeSliceNet
        run: dotnet test --configuration Release
  coverage:
    needs: unittest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup .NET Core
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: 5.0.100
      - name: Install dependencies
        working-directory: ./TimeSliceNet
        run: dotnet restore
      - name: Install coverlet.msbuild in TimeSliceTests
        working-directory: ./TimeSliceNet/TimeSliceTests
        run: dotnet add package coverlet.msbuild
      - name: Install coverlet.msbuild in WebApplicationTests
        working-directory: ./TimeSliceNet/ExampleWebApplicationTests
        run: dotnet add package coverlet.msbuild
      - name: Measure Test Coverage
        working-directory: ./TimeSliceNet
        run: dotnet test /p:Threshold=95 /p:Include="[TimeSlice.*]*,8TimeSliceEntityFrameworkExtensions.*]*" /p:ThresholdType=line /p:CollectCoverage=true /p:SkipAutoProps=true /p:CoverletOutputFormat=lcov --configuration Release
        # ToDo: increase the threshold over time.
